function voice_link_export_summary(cfg, voiceRows, outageRows, simRows, compareRows, simStatus)
%VOICE_LINK_EXPORT_SUMMARY_LATEX Write a Markdown summary and LaTeX table snippets.

summaryPath = fullfile(cfg.outputDir, "matlab_voice_link_validation_summary.md");
texPath = fullfile(cfg.outputDir, "matlab_voice_link_table_snippets.tex");

mainVoice = voiceRows(voiceRows.voice_rate_bps == cfg.voice.mainRateBps, :);
sigma6 = outageRows(abs(outageRows.sigma_db - 6.0) < 1e-9, :);

fid = fopen(summaryPath, "w");
fprintf(fid, "# voice-link MATLAB/Simulink Validation Summary\n\n");
fprintf(fid, "- MATLAB voice Monte Carlo samples: %d\n", cfg.nMcVoice);
fprintf(fid, "- MATLAB outage-capacity samples: %d\n", cfg.nMcCapacity);
fprintf(fid, "- Simulink status: %s\n\n", simStatus);

fprintf(fid, "## Main 2.4 kbps Voice Availability\n\n");
fprintf(fid, "| Scenario | Availability | P10 Eb/N0 (dB) | Median Eb/N0 (dB) |\n");
fprintf(fid, "|---|---:|---:|---:|\n");
for i = 1:height(mainVoice)
    fprintf(fid, "| %s | %.5f | %.3f | %.3f |\n", ...
        mainVoice.label(i), mainVoice.availability(i), ...
        mainVoice.p10_ebn0_db(i), mainVoice.median_ebn0_db(i));
end

if ~isempty(sigma6)
    fprintf(fid, "\n## Reference Outage Capacity\n\n");
    fprintf(fid, "At gamma0 = %.4f dB, sigma = 6 dB, epsilon = %.1e:\n\n", ...
        cfg.outage.gamma0Db, cfg.outage.epsilon);
    fprintf(fid, "- MATLAB MC: %.6f bit/s/Hz\n", sigma6.c_mc(1));
    fprintf(fid, "- Exact lognormal: %.6f bit/s/Hz\n", sigma6.c_exact(1));
    fprintf(fid, "- Chernoff lower bound: %.6f bit/s/Hz\n", sigma6.c_chernoff_lb(1));
end

if ~isempty(compareRows)
    fprintf(fid, "\n## Cross-Implementation Errors\n\n");
    fprintf(fid, "See `matlab_python_validation.csv` for the full table.\n");
    fprintf(fid, "Maximum absolute error: %.6g\n", max(compareRows.absolute_error));
end
fclose(fid);

fid = fopen(texPath, "w");
fprintf(fid, "%% Auto-generated by matlab_voice_link/voice_link_export_summary.m\n");
fprintf(fid, "\\begin{table}[!t]\n\\centering\n");
fprintf(fid, "\\caption{MATLAB/Simulink co-simulation alignment for the 2.4 kbps voice-link voice bearer.}\n");
fprintf(fid, "\\label{tab:matlab-simulink-cosim-alignment}\n");
fprintf(fid, "\\scriptsize\n");
fprintf(fid, "\\begin{tabular}{lccc}\n\\toprule\n");
fprintf(fid, "Scenario & MATLAB availability & P10 $E_b/N_0$ & Median $E_b/N_0$\\\\\n");
fprintf(fid, "\\midrule\n");
for i = 1:height(mainVoice)
    fprintf(fid, "%s & %.4f & %.2f dB & %.2f dB\\\\\n", ...
        mainVoice.label(i), mainVoice.availability(i), ...
        mainVoice.p10_ebn0_db(i), mainVoice.median_ebn0_db(i));
end
fprintf(fid, "\\bottomrule\n\\end{tabular}\n\\end{table}\n");
fclose(fid);

fprintf("Wrote %s\n", summaryPath);
fprintf("Wrote %s\n", texPath);
end
