#!/usr/bin/env python3
"""Python orchestration for the Step 1 MATLAB/Simulink co-simulation.

Python remains the top-level runner, but the reference Step 1 voice
availability table is generated by MATLAB/Simulink with PHY-calibrated
thresholds. This module writes the file-contract manifest, invokes MATLAB, and
promotes strict Simulink outputs into the canonical Python result location.
"""
from __future__ import annotations

import csv
import hashlib
import json
import math
import os
import shutil
import subprocess
from pathlib import Path
from typing import Iterable

try:
    from .paths import GEO_SATPHONE_DIR, MATLAB_STEP1_RESULTS_DIR, ROOT
except ImportError:  # Allow direct execution during debugging.
    from paths import GEO_SATPHONE_DIR, MATLAB_STEP1_RESULTS_DIR, ROOT


SCHEMA_VERSION = "step1-cosim-manifest-v1"
REFERENCE_SOURCE = "matlab_simulink_phy_threshold"
VOICE_RATES_BPS = [1200.0, 2400.0, 4000.0]
LEGACY_THRESHOLDS_DB = [-1.0, 0.7, 2.2]
STEP1_KEYS = ["open", "suburban", "urban", "car", "indoor_window"]
SCENARIO_KEYS = ["open_plain", "forest_edge", "canyon_valley", "moving_trail", "tent_shelter"]
SCENARIO_LABELS = ["Open plain", "Forest edge", "Canyon valley", "Moving trail", "Tent/shelter"]


def _p_los_elevation(elev_deg: float, scenario: str) -> float:
    shift = {"open": 12.0, "suburban": 18.0, "urban": 26.0, "car": 30.0, "indoor_window": 38.0}[scenario]
    scale = {"open": 6.0, "suburban": 7.0, "urban": 8.0, "car": 8.5, "indoor_window": 9.5}[scenario]
    cap = {"open": 0.98, "suburban": 0.92, "urban": 0.78, "car": 0.60, "indoor_window": 0.38}[scenario]
    return cap / (1.0 + math.exp(-(elev_deg - shift) / scale))


def _scenario_rows() -> list[dict[str, object]]:
    elev_deg = 45.0
    sigma = [2.5, 4.0, 7.0, 6.0, 9.0]
    theta_mean = [8.0, 13.0, 20.0, 25.0, 30.0]
    theta_std = [5.0, 8.0, 12.0, 14.0, 16.0]
    nlos_loss = [8.0, 12.0, 18.0, 20.0, 26.0]
    rows: list[dict[str, object]] = []
    for i, step1_key in enumerate(STEP1_KEYS):
        p_los = _p_los_elevation(elev_deg, step1_key)
        rows.append(
            {
                "scenario_key": SCENARIO_KEYS[i],
                "step1_key": step1_key,
                "label": SCENARIO_LABELS[i],
                "elevation_deg": elev_deg,
                "p_los": p_los,
                "sigma_db": sigma[i],
                "theta_mean_deg": theta_mean[i],
                "theta_std_deg": theta_std[i],
                "nlos_loss_db": nlos_loss[i],
                "p_ll": p_los,
                "p_nn": 1.0 - p_los,
            }
        )
    return rows


def _canonical_json(data: object) -> str:
    return json.dumps(data, ensure_ascii=False, indent=2, sort_keys=True)


def file_sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def write_input_manifest() -> Path:
    MATLAB_STEP1_RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    manifest = {
        "schema_version": SCHEMA_VERSION,
        "project_root": "<repo-root>",
        "seed": 20260608,
        "n_mc_voice": 200_000,
        "n_mc_capacity": 1_000_000,
        "strict_simulink": True,
        "authoritative_source": REFERENCE_SOURCE,
        "link": {
            "uplink_mhz": 1995.0,
            "downlink_mhz": 2185.0,
            "distance_km": 36_000.0,
            "bandwidth_hz": 31.25e3,
            "pt_dbm": 34.0,
            "sat_gr_dbi": 40.0,
            "pol_loss_db": 0.5,
            "extra_loss_db": 1.0,
            "nf_db": 2.0,
            "g_peak_dbi": 2.0,
            "g_min_dbi": -10.0,
            "posture_exponent": 1.7,
        },
        "voice": {
            "rate_bps": VOICE_RATES_BPS,
            "legacy_threshold_ebn0_db": LEGACY_THRESHOLDS_DB,
            "main_rate_bps": 2400.0,
            "threshold_source": "matlab_communications_toolbox_phy_calibration",
            "target_fer": 1e-2,
        },
        "scenarios": _scenario_rows(),
    }
    path = MATLAB_STEP1_RESULTS_DIR / "step1_cosim_input_manifest.json"
    path.write_text(_canonical_json(manifest) + "\n", encoding="utf-8")
    return path


def find_matlab_executable() -> Path:
    env_path = os.environ.get("MATLAB_EXE")
    candidates: list[Path] = []
    if env_path:
        env_candidate = Path(env_path)
        if not env_candidate.exists():
            raise SystemExit(f"MATLAB_EXE was set but does not exist: {env_candidate}")
        return env_candidate
    path_tool = shutil.which("matlab")
    if path_tool:
        candidates.append(Path(path_tool))
    candidates.append(Path(r"D:\matlab\bin\matlab.exe"))
    for candidate in candidates:
        if candidate.exists():
            return candidate
    raise SystemExit(
        "MATLAB executable not found. Set MATLAB_EXE, put matlab on PATH, "
        "or install it at D:\\matlab\\bin\\matlab.exe."
    )


def _matlab_quote(path: Path) -> str:
    return str(path).replace("'", "''")


def matlab_batch_command(manifest_path: Path) -> str:
    matlab_dir = ROOT / "matlab_step1"
    return (
        "try, "
        f"cd('{_matlab_quote(matlab_dir)}'); "
        f"run_step1_cosim_strict('{_matlab_quote(manifest_path)}'); "
        "catch ME, disp(getReport(ME,'extended','hyperlinks','off')); exit(1); "
        "end; exit(0);"
    )


def run_matlab_cosim(matlab_exe: Path | None = None) -> Path:
    manifest_path = write_input_manifest()
    matlab = matlab_exe or find_matlab_executable()
    cmd = [str(matlab), "-batch", matlab_batch_command(manifest_path)]
    print("\n==> Run strict Step 1 MATLAB/Simulink co-simulation", flush=True)
    print("$ " + " ".join(cmd), flush=True)
    result = subprocess.run(cmd, cwd=ROOT)
    if result.returncode != 0:
        raise SystemExit(result.returncode)
    return manifest_path


def _read_csv(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8-sig") as f:
        return list(csv.DictReader(f))


def _write_csv(path: Path, rows: list[dict[str, object]], fieldnames: Iterable[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=list(fieldnames))
        writer.writeheader()
        writer.writerows(rows)


def _load_json(path: Path) -> dict[str, object]:
    return json.loads(path.read_text(encoding="utf-8"))


def _float(row: dict[str, str], key: str) -> float:
    return float(row[key])


def validate_and_promote(manifest_path: Path | None = None) -> None:
    manifest_path = manifest_path or (MATLAB_STEP1_RESULTS_DIR / "step1_cosim_input_manifest.json")
    manifest = _load_json(manifest_path)
    manifest_hash = file_sha256(manifest_path)
    sim_path = MATLAB_STEP1_RESULTS_DIR / "simulink_voice_availability.csv"
    threshold_path = MATLAB_STEP1_RESULTS_DIR / "voice_threshold_from_phy.csv"
    status_path = MATLAB_STEP1_RESULTS_DIR / "step1_cosim_status.json"
    for path in [sim_path, threshold_path, status_path]:
        if not path.exists():
            raise SystemExit(f"Missing required MATLAB/Simulink co-sim output: {path}")

    status = _load_json(status_path)
    if status.get("strict_simulink") is not True:
        raise SystemExit("MATLAB co-sim status does not declare strict_simulink=true.")
    if status.get("simulink_mode") != "matlab_function_block":
        raise SystemExit(f"Strict Simulink run did not use MATLAB Function block mode: {status.get('simulink_mode')}")
    if status.get("authoritative_source") != REFERENCE_SOURCE:
        raise SystemExit("Unexpected reference source in MATLAB co-sim status.")

    sim_rows = _read_csv(sim_path)
    thresholds = _read_csv(threshold_path)
    required_rates = {float(x) for x in manifest["voice"]["rate_bps"]}  # type: ignore[index]
    required_step1 = {str(s["step1_key"]) for s in manifest["scenarios"]}  # type: ignore[index]
    seen = {(row["step1_key"], _float(row, "voice_rate_bps")) for row in sim_rows}
    missing = sorted((scenario, rate) for scenario in required_step1 for rate in required_rates if (scenario, rate) not in seen)
    if missing:
        raise SystemExit(f"MATLAB/Simulink availability output is missing rows: {missing}")
    if len(sim_rows) != len(required_rates) * len(required_step1):
        raise SystemExit(f"Unexpected Simulink row count: {len(sim_rows)}")

    threshold_by_rate = {_float(row, "voice_rate_bps"): _float(row, "phy_threshold_ebn0_db") for row in thresholds}
    for rate in required_rates:
        if rate not in threshold_by_rate:
            raise SystemExit(f"Missing PHY threshold for voice rate {rate}")

    canonical_rows: list[dict[str, object]] = []
    for row in sim_rows:
        rate = _float(row, "voice_rate_bps")
        threshold = _float(row, "threshold_ebn0_db")
        expected = threshold_by_rate[rate]
        if abs(threshold - expected) > 1e-6:
            raise SystemExit(f"Threshold mismatch for {row['step1_key']} {rate}: {threshold} != {expected}")
        canonical_rows.append(
            {
                "scenario": row["step1_key"],
                "scenario_key": row["scenario_key"],
                "scenario_label": row["label"],
                "elevation_deg": 45.0,
                "p_los": _float(row, "p_los"),
                "voice_rate_bps": rate,
                "threshold_ebn0_db": threshold,
                "threshold_source": "phy_calibrated",
                "availability": _float(row, "availability"),
                "p10_ebn0_db": _float(row, "p10_ebn0_db"),
                "median_ebn0_db": _float(row, "median_ebn0_db"),
                "mean_mos_proxy": _float(row, "mean_mos_proxy"),
            }
        )

    canonical_fields = [
        "scenario",
        "scenario_key",
        "scenario_label",
        "elevation_deg",
        "p_los",
        "voice_rate_bps",
        "threshold_ebn0_db",
        "threshold_source",
        "availability",
        "p10_ebn0_db",
        "median_ebn0_db",
        "mean_mos_proxy",
    ]
    GEO_SATPHONE_DIR.mkdir(parents=True, exist_ok=True)
    _write_csv(GEO_SATPHONE_DIR / "voice_availability.csv", canonical_rows, canonical_fields)

    scenarios = []
    for sc in manifest["scenarios"]:  # type: ignore[index]
        sc_rows = [r for r in canonical_rows if r["scenario_key"] == sc["scenario_key"]]
        main = next(r for r in sc_rows if abs(float(r["voice_rate_bps"]) - 2400.0) < 1e-9)
        scenarios.append(
            {
                **sc,
                "voice_availability_2400": main["availability"],
                "p10_ebn0_2400_db": main["p10_ebn0_db"],
                "median_ebn0_2400_db": main["median_ebn0_db"],
            }
        )
    service_baseline = {
        "schema_version": "step1-service-baseline-v1",
        "authoritative": True,
        "source": REFERENCE_SOURCE,
        "manifest_sha256": manifest_hash,
        "thresholds": threshold_by_rate,
        "scenarios": scenarios,
    }
    (GEO_SATPHONE_DIR / "step1_service_baseline.json").write_text(
        _canonical_json(service_baseline) + "\n", encoding="utf-8"
    )

    provenance = {
        "authoritative": True,
        "source": REFERENCE_SOURCE,
        "manifest_sha256": manifest_hash,
        "matlab_status": status,
        "promoted_files": {
            "voice_availability": str(GEO_SATPHONE_DIR / "voice_availability.csv"),
            "service_baseline": str(GEO_SATPHONE_DIR / "step1_service_baseline.json"),
        },
    }
    (GEO_SATPHONE_DIR / "voice_availability_provenance.json").write_text(
        _canonical_json(provenance) + "\n", encoding="utf-8"
    )
    print("Promoted MATLAB/Simulink reference Step 1 availability outputs", flush=True)
    print(GEO_SATPHONE_DIR / "voice_availability.csv", flush=True)


def mark_python_only(reason: str) -> None:
    GEO_SATPHONE_DIR.mkdir(parents=True, exist_ok=True)
    provenance = {
        "authoritative": False,
        "source": "python_proxy",
        "reason": reason,
    }
    (GEO_SATPHONE_DIR / "voice_availability_provenance.json").write_text(
        _canonical_json(provenance) + "\n", encoding="utf-8"
    )
    service_baseline = {
        "schema_version": "step1-service-baseline-v1",
        "authoritative": False,
        "source": "python_proxy",
        "reason": reason,
        "scenarios": [],
        "thresholds": {},
    }
    (GEO_SATPHONE_DIR / "step1_service_baseline.json").write_text(
        _canonical_json(service_baseline) + "\n", encoding="utf-8"
    )


def run(seed: int | None = None) -> None:
    # The seed is part of the manifest contract. The argument is accepted only
    # for module-run symmetry with other project scripts.
    _ = seed
    manifest = run_matlab_cosim()
    validate_and_promote(manifest)


if __name__ == "__main__":
    run()
